# Generated by Django 4.2.17 on 2025-01-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_book', '0003_alter_comment_approved_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.IntegerField(choices=[(0, 'pc'), (1, 'stick'), (2, 'mg'), (3, 'g'), (4, 'kg'), (5, 'oz'), (6, 'lb'), (7, 'ml'), (8, 'cl'), (9, 'l'), (10, 'tsp'), (11, 'tbsp'), (12, 'floz'), (13, 'cup'), (14, 'pint'), (15, 'quart'), (16, 'gallon')], default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_needed', to='recipe_book.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='recipe_book.recipe')),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
    ]
