# Generated by Django 4.2.17 on 2025-01-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0004_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.IntegerField(choices=[(0, 'pc'), (1, 'stick'), (2, 'mg'), (3, 'g'), (4, 'kg'), (5, 'oz'), (6, 'lb'), (7, 'ml'), (8, 'cl'), (9, 'l'), (10, 'tsp'), (11, 'tbsp'), (12, 'floz'), (13, 'cup'), (14, 'pint'), (15, 'quart'), (16, 'gallon')], default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_used_in', to='recipe_book.recipe')),
            ],
        ),
    ]
