# Generated by Django 4.2.17 on 2025-01-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0006_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
